### PR TITLE
Pin next to the catalog version

### PR DESCRIPTION
**Pull request by vicb**

### CODE REVIEW

**Review by dario-piotrowicz — COMMENTED** [review]
What's the benefit of pinning `next` to the catalog?

If we were to have different `next` versions that would simply imply that we are testing our solution with different versions of the framework, which seems like a positive thing to me?

**Comment by vicb** [comment]
You should definitely work on improving testing (there is an issue related to that).

But for now I don't want to have to update the apps (to match the latest `Next`) while I'm working on the open next integration.

**Comment by vicb** [comment]
> these are also unpinned: [vercel-commerce/next-deps](https://github.com/opennextjs/opennextjs-cloudflare/blob/main/examples/vercel-commerce/package.json#L24-L26)

It's pinned (but not to the catalog version).

**Comment by dario-piotrowicz** [comment]
> It's pinned (but not to the catalog version).

yeah sorry that's what I meant 😅

**Review by dario-piotrowicz — APPROVED** [review]
I don't fully agree with this change but I'm not super against it (since we're doing this in the `create-next-app` example)

**Comment by vicb** [comment]
> I don't fully agree with this change but I'm not super against it (since we're doing this in the `create-next-app` example)

It's only temporary and we will improve tests as part of #108 

Thanks!

**Pull request merged**
